### ISSUE TITLE
Windows 10 Install Security Profiles Script wrong minimum Win ver

### ISSUE THREAD

**Issue by nitvit610** [vanvfields/Microsoft-365#10]
Install-Windows10SecurityProfiles.ps1
Windows 10 Baseline Compliance policy, description says minimum 1903 (10.0.18362) Windows version, however under device properties it is set to 1909 (10.0.18363).

In the script the description 1903 is set on line 1615 and the device properties 1909 is on line 1627

**Comment by vanvfields** [comment]
Right.
