### ISSUE TITLE
Script fails with a variable error

### ISSUE THREAD

**Issue by bboryczko** [vanvfields/Microsoft-365#14]
I am unable to execute the "Setp-Intune.ps1" script. It fails with an error. Is there a specific version of PowerShell required? I'm running version 5.1.19041.610. I have the AzureAD PS module installed. Running Windows 10 Enterprise Version 20H2.

```.\Setup-Intune.ps1

The variable '$global:authToken' cannot be retrieved because it has not been set.
At D:\IntuneScripts\Setup-Intune.ps1:849 char:4
+ if($global:authToken){
+    ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (global:authToken:String) [], RuntimeException
    + FullyQualifiedErrorId : VariableIsUndefined

You cannot call a method on a null-valued expression.
At D:\IntuneScripts\Setup-Intune.ps1:814 char:5
+     $errorResponse = $ex.Response.GetResponseStream()
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull

You cannot call a method on a null-valued expression.
At D:\IntuneScripts\Setup-Intune.ps1:896 char:1
+ $Sharepoint = $EnterpriseDomain.Split(".")[0]
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : InvokeMethodOnNull
```

**Comment by vanvfields** [comment]
I cannot reproduce this error.

**Comment by bboryczko** [comment]
So there is no help or hints you can offer if I'm having problems executing your script? Can you verify which PS version you are running? Or Windows version?

**Comment by vanvfields** [comment]
I don’t know what to tell you. I can run all my scripts without issue. Very vanilla, but entirely up to date Windows 10. Haven’t heard others complain either. Must be something on your end.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
